name: Test and upload coverage to Coveralls
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  upload-coverage-to-coveralls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install, Test and Create Coverage Report ğŸ”§
        run: |
          npm install
          mkdir .nyc_output || true
          npm run test:coverage
          mkdir reports || true
          ls la .nyc_output
          cp jest-coverage/coverage-final.json reports/from-jest.json
          cp cypress-coverage/coverage-final.json reports/from-cypress.json
          ls la reports
          npx nyc merge reports coverage.json && mv coverage.json .nyc_output/out.json
          npx nyc report --temp-dir .nyc_output --reporter lcov --reporter text --report-dir coverage

      - name: Coveralls ğŸš€
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
